### ISSUE TITLE
wdt: add support for dot (hidden) files transfer

### ISSUE THREAD

**Issue by kowshik** [facebook/wdt#113]
wdt does not copy dot files (i.e. hidden files/directories, example: /tmp/abc/.def and /tmp/.abc). It would be nice to have support for this. Here is the code that could be related to the lack of this support: https://github.com/facebook/wdt/blob/master/util/DirectorySourceQueue.cpp#L289.

**Comment by ldemailly** [comment]
my bad we already support dot files (code above does check for excluding only . or ..)
