### ISSUE TITLE
collect2: error ld returned 1 exit status

### ISSUE THREAD

**Issue by andreykirov** [facebook/wdt#119]
Hello,
I followed the build instructions and downloaded and compiled/installed required dependacies on Cygwin64 (run on Windows 8.1). However, when it comes to run make -j it gives me this:

Administrator@Injector1 ~/wdt/build
$ make -j
[ 12%] Built target folly4wdt
[ 82%] Built target wdt_min
[ 89%] Built target wdt
[ 92%] Linking CXX executable _bin/wdt/wdt.exe
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x1e7c): multiple definition of `google::LogMessage::LogMessage(char const*, int)'
libwdt_min.dll.a(d000256.o):(.text+0x0): first defined here
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x1edc): multiple definition of `google::LogMessage::LogMessage(char const*, int, int)'
libwdt_min.dll.a(d000258.o):(.text+0x0): first defined here
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x27d0): multiple definition of `google::LogMessage::~LogMessage()'
libwdt_min.dll.a(d000270.o):(.text+0x0): first defined here
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x2824): multiple definition of `google::LogMessage::stream()'
libwdt_min.dll.a(d000250.o):(.text+0x0): first defined here
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x5b5a): multiple definition of `google::LogMessageFatal::LogMessageFatal(char const*, int)'
libwdt_min.dll.a(d000324.o):(.text+0x0): first defined here
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x5bce): multiple definition of `google::LogMessageFatal::~LogMessageFatal()'
libwdt_min.dll.a(d000328.o):(.text+0x0): first defined here
/usr/local/lib/libglog.a(logging.cc.o):logging.cc:(.text+0x5f2f): multiple definition of `google::InitGoogleLogging(char const*)'
libwdt_min.dll.a(d000336.o):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/wdtbin.dir/build.make:152: recipe for target '_bin/wdt/wdt.exe' failed
make[2]: *** [_bin/wdt/wdt.exe] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/wdtbin.dir/all' failed
make[1]: *** [CMakeFiles/wdtbin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I am not 100% sure if this problem is caused by wdt ot glog? What would you recommend as a solution?

**Comment by ldemailly** [comment]
hey there, sorry for the delay in reply, we've been a bit busy - also I only have cygwin on my personal laptop at home and it's not fully supported/working yet

this being said,

your problem would probably be solved if you use -DBUILD_SHARED_LIBS=off in your cmake
(I think mix of shared and static linking isn't working)

but then again, cygwin isn't correctly working yet, see issue #114

**Comment by ldemailly** [comment]
closing assuming static linking fixed it - reopen if that's not the case
