### ISSUE TITLE
Can't build, no gmock library

### ISSUE THREAD

**Issue by jalavosus** [facebook/wdt#12]
Attempting to build on OS X 10.10

    [ 75%] Linking CXX shared library libwdt4tests.dylib

    ld: warning: directory not found for option '-L/Users/james/wdt/gmock/src/gmock-build/Debug'

    ld: library not found for -lgmock

    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    make[2]: *** [libwdt4tests.dylib] Error 1

    make[1]: *** [CMakeFiles/wdt4tests.dir/all] Error 2

    make[1]: *** Waiting for unfinished jobs....

    -- gmock download command succeeded.  See also /Users/james/wdt/gmock/src/gmock-stamp/gmock-download-*.log

    [ 80%] No patch step for 'gmock'

    [ 80%] No update step for 'gmock'

    [ 82%] Performing configure step for 'gmock'

    [ 84%] Linking CXX executable _bin/wdt/wdt

    [ 84%] Built target wdt

    -- gmock configure command succeeded.  See also /Users/james/wdt/gmock/src/gmock-stamp/gmock-configure-*.log

    [ 86%] Performing build step for 'gmock'

    -- gmock build command succeeded.  See also /Users/james/wdt/gmock/src/gmock-stamp/gmock-build-*.log

    [ 88%] No install step for 'gmock'

    [ 91%] Completed 'gmock'

    [ 91%] Built target gmock

    make: *** [all] Error 2

Extra detail: am using fish shell. Is that an issue?

**Comment by ldemailly** [comment]
redo make without -j it should complete?



—

**Comment by jalavosus** [comment]
Yup, that did it.

**Comment by ldemailly** [comment]
I will document this, it is kind of a bug in cmake



—

**Comment by ldemailly** [comment]
Filled http://www.cmake.org/Bug/view.php?id=15663

**Comment by ldemailly** [comment]
turns out there is was a bug in our cmake, fix incoming
