### ISSUE TITLE
wdt make error on Ubuntu 14.04.4 LTS \n \l

### ISSUE THREAD

**Issue by cldy007** [facebook/wdt#120]
I encounter an error as below in process of make , did i make something wrong?

[  2%] Building CXX object CMakeFiles/folly4wdt.dir/home/cl/facebook/folly/folly/Conv.cpp.o
[  5%] Building CXX object CMakeFiles/folly4wdt.dir/home/cl/facebook/folly/folly/Demangle.cpp.o
[  8%] Building CXX object CMakeFiles/folly4wdt.dir/home/cl/facebook/folly/folly/Checksum.cpp.o
Linking CXX shared library libfolly4wdt.so
[  8%] Built target folly4wdt
[ 11%] Building CXX object CMakeFiles/wdt_min.dir/util/WdtSocket.cpp.o
In file included from /home/cl/facebook/wdt/../wdt/Reporting.h:26:0,
                 from /home/cl/facebook/wdt/../wdt/util/CommonImpl.h:13,
                 from /home/cl/facebook/wdt/../wdt/util/WdtSocket.h:6,
                 from /home/cl/facebook/wdt/util/WdtSocket.cpp:1:
/home/cl/facebook/wdt/../folly/folly/RWSpinLock.h: In static member function 'static __m128i folly::detail::RWTicketIntTrait<64u>::fromInteger(uint64_t)':
/home/cl/facebook/wdt/../folly/folly/RWSpinLock.h:491:34: error: '_mm_cvtsi64_si128' was not declared in this scope
     return _mm_cvtsi64_si128(from);
                                  ^
/home/cl/facebook/wdt/../folly/folly/RWSpinLock.h: In static member function 'static uint64_t folly::detail::RWTicketIntTrait<64u>::toInteger(__m128i)':
/home/cl/facebook/wdt/../folly/folly/RWSpinLock.h:494:32: error: '_mm_cvtsi128_si64' was not declared in this scope
     return _mm_cvtsi128_si64(in);
                                ^
make[2]: **\* [CMakeFiles/wdt_min.dir/util/WdtSocket.cpp.o] Error 1
make[1]: **\* [CMakeFiles/wdt_min.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ldemailly** [comment]
it's possible folly changed and something is broken
I restarted the travis build to confirm:
https://travis-ci.org/facebook/wdt/jobs/126781147

**Comment by ldemailly** [comment]
looks like it's still compiling fine on ubuntu from travis-ci 
maybe your system doesn't have SSE ? (though that's supposed to be detected in folly Portability.h)

**Comment by cldy007** [comment]
@ldemailly  thanks a lot!
Actually , I run the make process on a 32bit ubuntu...
Can wdt run on 32bit system?

**Comment by ldemailly** [comment]
I never tried, we only have 64 bit OSes here :-) in theory it should/I don't see why not,
but it seems folly may have some issue patches welcome :-)

**Comment by ldemailly** [comment]
going to close this, reopen if you need/provide a patch
