### ISSUE TITLE
cmd line way to overload the hostname (for instance to external ip)

### ISSUE THREAD

**Issue by ldemailly** [facebook/wdt#123]
right now we rely on gethostname in receiver

https://github.com/facebook/wdt/blob/df59e6c2171730e7d602c7df3636c393345f6d18/Receiver.cpp#L225

to create a url which will work on the sender (externally resolvable name) - this isn't always the case

let's expose -hostname to change that in the transfer request

**Comment by rjammala** [comment]
@ldemailly Looks like this is related to what I observed when I create a linked clone of the Ubuntu VM and used the ip address. Please let me know if that is not the case.
