### ISSUE TITLE
increase number of ports can't improve transmission rate

### ISSUE THREAD

**Issue by gosyang** [facebook/wdt#128]
hi, can you help me? ^ ^

# Problem
Couldn't impove the transmission rate no matter how I change number of ports. Always maintain 160Mbyts/s. 
And test one tcp bandwith is 3.19 Gbits/sec with iperf3.
Is there a paramter limit the speed I don't know?

# Environment
Linux version 3.2.60 (root@ubuntu-12) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) )

# Commands
## Sender
`wdt --directory xx -avg_mbytes_per_sec 800  --transfer_id=169 --destination xx --start_port 2222 -num_ports=10 --encryption_type=none -throttler_bucket_limit 800`

## Reciever
`wdt --run_as_daemon=false --start_port 2222 --transfer_id=169 -num_ports 10 --encryption_type=none -avg_mbytes_per_sec 800 -throttler_bucket_limit 800`

### Sender log
> I0726 11:09:40.133309 18856 EncryptionUtils.cpp:82] wdt>	Openssl library initialized
I0726 11:09:40.133471 18856 WdtResourceController.cpp:29] wdt>	Updated max number of senders for _root controller_ to 0
I0726 11:09:40.133491 18856 WdtResourceController.cpp:22] wdt>	Updated max number of receivers for _root controller_ to 0
I0726 11:09:40.133505 18856 Throttler.cpp:77] wdt>	No average rate specified
I0726 11:09:40.133517 18856 Throttler.cpp:84] wdt>	No peak rate specified
I0726 11:09:40.133535 18856 WdtFlags.cpp:63] wdt>	Running WDT 1.26.1606240 p 26
I0726 11:09:40.134104 18856 WdtOptions.cpp:56] wdt>	start_port is specified, setting static_ports true
I0726 11:09:40.134165 18856 WdtFlags.cpp:63] wdt>	Running WDT 1.26.1606240 p 26
I0726 11:09:40.134634 18856 WdtOptions.cpp:56] wdt>	start_port is specified, setting static_ports true
I0726 11:09:40.134670 18856 Wdt.cpp:25] wdt>	One time initialization of WDT for wdt
W0726 11:09:40.134701 18856 Throttler.cpp:44] wdt>	Per thread peak rate should be greater than per thread average rate. Making peak rate 1.2 times the average rate
I0726 11:09:40.134728 18856 Throttler.cpp:105] wdt>	Updating the rates avgRateBytesPerSec : 8.38861e+08 bucketRateBytesPerSec : 1.00663e+09 bytesTokenBucketLimit : 8.38861e+08
I0726 11:09:40.134798 18856 wdtCmdLine.cpp:357] wdt>	Making Sender with encryption set = 0
I0726 11:09:40.134841 18856 WdtResourceController.cpp:359] wdt>	First time Global is seen, creating.
I0726 11:09:40.134874 18856 WdtResourceController.cpp:29] wdt>	Updated max number of senders for Global to 0
I0726 11:09:40.134902 18856 WdtResourceController.cpp:22] wdt>	Updated max number of receivers for Global to 1
W0726 11:09:40.134937 18856 Throttler.cpp:44] wdt>	Per thread peak rate should be greater than per thread average rate. Making peak rate 1.2 times the average rate
I0726 11:09:40.134963 18856 Throttler.cpp:105] wdt>	Updating the rates avgRateBytesPerSec : 8.38861e+08 bucketRateBytesPerSec : 1.00663e+09 bytesTokenBucketLimit : 8.38861e+08
I0726 11:09:40.135017 18856 Sender.cpp:48] wdt>	WDT Sender 1.26.1606240 p 26
I0726 11:09:40.135067 18856 DirectorySourceQueue.cpp:128] wdt>	Root dir now xx
I0726 11:09:40.135115 18856 WdtBase.cpp:93] wdt>	using wdt protocol version 26
I0726 11:09:40.135154 18856 WdtResourceController.cpp:379] wdt>	Successfully added a sender for Global
I0726 11:09:40.135190 18856 Sender.cpp:353] wdt>	Client (sending) to xx, Using ports [ 2222 2223 2224 2225 2226 2227 2228 2229 2230 2231 ]
I0726 11:09:40.135227 18856 Sender.cpp:364] wdt>	Skipping throttler setup. External throttler set.Throttler details : avgRate: 800 Mbytes/sec, peakRate: 960 Mbytes/sec, bucketLimit: 800 Mbytes, throttlerLogTimeMillis: 0
I0726 11:09:40.135659 18857 DirectorySourceQueue.cpp:241] wdt>	Exploring root dir xx include_pattern :  exclude_pattern :  prune_dir_pattern :
I0726 11:09:40.135679 18858 Sender.cpp:42] wdt>	Starting a new transfer 169 to xx
I0726 11:09:40.136307 18868 Sender.cpp:457] wdt>	Progress reporter tracking every 20 ms
I0726 11:09:40.137056 18857 DirectorySourceQueue.cpp:390] wdt>	Number of files explored: 2 opened 0 with direct 0 errors false
I0726 11:09:40.148025 18864 SenderThread.cpp:85] wdt>	Thread[6, port: 2228]  Connection took 1 attempt(s) and 0.0122782 seconds. port 2228
I0726 11:09:40.149909 18858 SenderThread.cpp:85] wdt>	Thread[0, port: 2222]  Connection took 1 attempt(s) and 0.0141794 seconds. port 2222
I0726 11:09:40.150521 18867 SenderThread.cpp:85] wdt>	Thread[9, port: 2231]  Connection took 1 attempt(s) and 0.0143583 seconds. port 2231
I0726 11:09:40.153287 18859 SenderThread.cpp:85] wdt>	Thread[1, port: 2223]  Connection took 1 attempt(s) and 0.01755 seconds. port 2223
I0726 11:09:40.154496 18863 SenderThread.cpp:85] wdt>	Thread[5, port: 2227]  Connection took 1 attempt(s) and 0.0187376 seconds. port 2227
[                                                 ]  0% 0.0 0.0 Mbytes/s  I0726 11:09:40.157521 18861 SenderThread.cpp:85] wdt>	Thread[3, port: 2225]  Connection took 1 attempt(s) and 0.0217741 seconds. port 2225
I0726 11:09:40.158093 18860 SenderThread.cpp:85] wdt>	Thread[2, port: 2224]  Connection took 1 attempt(s) and 0.0223499 seconds. port 2224
I0726 11:09:40.159404 18862 SenderThread.cpp:85] wdt>	Thread[4, port: 2226]  Connection took 1 attempt(s) and 0.0236502 seconds. port 2226
I0726 11:09:40.159641 18865 SenderThread.cpp:85] wdt>	Thread[7, port: 2229]  Connection took 1 attempt(s) and 0.0237055 seconds. port 2229
I0726 11:09:40.164726 18866 SenderThread.cpp:85] wdt>	Thread[8, port: 2230]  Connection took 1 attempt(s) and 0.028654 seconds. port 2230
[=================================================] 100% 159.3 Mbytes/s          I0726 11:10:38.007952 18859 SenderThread.cpp:915] wdt>	Thread[1, port: 2223]  Port 2223 done. Transfer status = OK. Number of blocks transferred = 113. Data Mbytes = 904. Header Kbytes = 3.64258 (0.000393496% overhead). Total bytes = 947916434. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 15.6206 Mbytes/sec
I0726 11:10:38.008256 18867 SenderThread.cpp:915] wdt>	Thread[9, port: 2231]  Port 2231 done. Transfer status = OK. Number of blocks transferred = 120. Data Mbytes = 960. Header Kbytes = 3.85645 (0.000392298% overhead). Total bytes = 1006636909. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 16.5884 Mbytes/sec
I0726 11:10:38.008378 18858 SenderThread.cpp:915] wdt>	Thread[0, port: 2222]  Port 2222 done. Transfer status = OK. Number of blocks transferred = 116. Data Mbytes = 928. Header Kbytes = 3.73242 (0.000392774% overhead). Total bytes = 973082350. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 16.0352 Mbytes/sec
I0726 11:10:38.008381 18862 SenderThread.cpp:915] wdt>	Thread[4, port: 2226]  Port 2226 done. Transfer status = OK. Number of blocks transferred = 117. Data Mbytes = 936. Header Kbytes = 3.76367 (0.000392677% overhead). Total bytes = 981470990. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 16.1735 Mbytes/sec
I0726 11:10:38.008721 18864 SenderThread.cpp:915] wdt>	Thread[6, port: 2228]  Port 2228 done. Transfer status = OK. Number of blocks transferred = 113. Data Mbytes = 904. Header Kbytes = 3.64258 (0.000393496% overhead). Total bytes = 947916434. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 15.6205 Mbytes/sec
I0726 11:10:38.010061 18865 SenderThread.cpp:915] wdt>	Thread[7, port: 2229]  Port 2229 done. Transfer status = OK. Number of blocks transferred = 117. Data Mbytes = 936. Header Kbytes = 3.76465 (0.000392779% overhead). Total bytes = 981470991. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 16.1731 Mbytes/sec
I0726 11:10:38.010124 18860 SenderThread.cpp:915] wdt>	Thread[2, port: 2224]  Port 2224 done. Transfer status = OK. Number of blocks transferred = 114. Data Mbytes = 912. Header Kbytes = 3.67188 (0.000393182% overhead). Total bytes = 956305072. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 15.7583 Mbytes/sec
I0726 11:10:38.010964 18866 SenderThread.cpp:915] wdt>	Thread[8, port: 2230]  Port 2230 done. Transfer status = OK. Number of blocks transferred = 116. Data Mbytes = 928. Header Kbytes = 3.73438 (0.00039298% overhead). Total bytes = 973082352. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 16.0346 Mbytes/sec
I0726 11:10:38.011018 18863 SenderThread.cpp:915] wdt>	Thread[5, port: 2227]  Port 2227 done. Transfer status = OK. Number of blocks transferred = 112. Data Mbytes = 896. Header Kbytes = 3.61719 (0.000394242% overhead). Total bytes = 939527800. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 15.4816 Mbytes/sec
I0726 11:10:38.011028 18861 SenderThread.cpp:915] wdt>	Thread[3, port: 2225]  Port 2225 done. Transfer status = OK. Number of blocks transferred = 114. Data Mbytes = 912. Header Kbytes = 3.67188 (0.000393182% overhead). Total bytes = 956305072. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none. Total throughput = 15.7581 Mbytes/sec
I0726 11:10:38.011127 18861 Sender.cpp:29] wdt>	Last thread finished 57.8759 for transfer id 169
I0726 11:10:38.011315 18856 Reporting.cpp:128] wdt>	Error code summary OK
[=================================================] 100% 159.2 Mbytes/s
I0726 11:10:38.011368 18856 Sender.cpp:322] wdt>	Total sender time = 57.8759 seconds (0.0016851 dirTime). Transfer summary : Transfer status = OK. Number of files transferred = 2. Data Mbytes = 9216. Header Kbytes = 37.0977 (0.000393101% overhead). Total bytes = 9663714404. Wasted bytes due to failure = 0 (0% overhead). Encryption type = none.
wdt>	Total sender throughput = 159.238 Mbytes/sec (159.242 Mbytes/sec pure transfer rate)
I0726 11:10:38.011420 18856 WdtResourceController.cpp:154] wdt>	Released the sender with id 169
I0726 11:10:38.011432 18856 Wdt.cpp:99] wdt>	wdtSend for Global xx  ended with OK
I0726 11:10:38.011989 18856 wdtCmdLine.cpp:367] wdt>	Returning with OK exit code
I0726 11:10:38.012017 18856 WdtResourceController.cpp:294] wdt>	Shutting down the controller (0 senders 0 receivers)

**Comment by nikunjy** [comment]
There are some factors that can limit your speed. 

1. Your source directory where the file is being copied from. Can you try doing this test using /dev/shm ? Because if you are using a disk then your files are going to be read slow. iperf3 uses data generated on the fly 

2. Your tcp settings might not be tuned properly. This can be things like buffer size, limit output bytes etc .

**Comment by gosyang** [comment]
Thanks! It's really the problem of HDD highest read speed about 160MB/s.

**Comment by ldemailly** [comment]
@nikunjy thanks a lot for having answered while I was away !
