### ISSUE TITLE
Linux 3.10 x86_64

### ISSUE THREAD

**Issue by abhinay-aruva** [facebook/wdt#133]
i am seeing issues on compiling the code on Linux Env. can you provide steps and depended list to compile the code on Linux env.

**Comment by abhinay-aruva** [comment]
few more errors 
compiling glog module seeing below error message,

hostnae@linux glog]# make -j 16
CDPATH="${ZSH_VERSION+."&& cd . && aclocal-1.14 I m4
/bin/sh :  aclocal-1.14 : command not found
make **** [aclocal.m4] Error 127

can someone help me in fixing this error message.

**Comment by ldemailly** [comment]
trying installing glog from binary ?

you can see all the build steps on travis-ci : for instance : https://travis-ci.org/facebook/wdt/jobs/163287753

and https://github.com/facebook/wdt/blob/master/build/travis_linux.sh

**Comment by abhinay-aruva** [comment]
Thank You ... travis_linux.sh script work well.
still i am seeing issues in compiling /wdt code.

cmake-3.3.2-Linux-x86_64.sh this doesn’t work  ... any suggestion in version which can use on RHEL linux x86. ?

earlier i tired with wdt_cont_build_setup.sh  failed to compile /wdt files. 

Before we compile /wdt what are things i need to make sure to install on my RHEL box version 6/7 ?

**Comment by ldemailly** [comment]
I am not clear which version of linux you are using but you need to get a recent cmake a either installing a pre built binary or building cmake from source: see http://cmake.org/

**Comment by ldemailly** [comment]
also please included the exact command you ran and the full output/result
https://cmake.org/download/

**Comment by ldemailly** [comment]
I'll assume you managed to get it work - if not reopen - thanks for trying WDT !
