### ISSUE TITLE
invalid pointer in running tests

### ISSUE THREAD

**Issue by zxpan** [facebook/wdt#141]
I am running the tests with this commit `779a693f59ae41dcef5fb2760d1fe982a56e7349`,  observed following errors:

      Start 20: WdtOverwriteTest
*** Error in `./_bin/wdt/wdt': free(): invalid pointer: 0x00002b86c4000930 ***

*** Error in `./_bin/wdt/wdt': free(): invalid pointer: 0x00002b9a18000930 ***
20/23 Test #20: WdtOverwriteTest .................***Failed   14.11 sec

Would like to bring your attention if this is indeed an authentic issue.

My environment: Ububtu 14.04, g++-4.9

**Comment by ldemailly** [comment]
which version of openssl are you using ?
can you run with asan maybe ?

**Comment by zxpan** [comment]
I am using "OpenSSL 1.0.1f 6 Jan 2014".

The core dump for running ./test/wdt_overwrite_test.py
(gdb) bt
#0  0x00007fd8e1478c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fd8e147c028 in __GI_abort () at abort.c:89
#2  0x00007fd8e14b52a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fd8e15c36b0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fd8e14c155e in malloc_printerr (ptr=<optimized out>, str=0x7fd8e15bf801 "free(): invalid pointer", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fd8e10c5fcd in CRYPTO_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00007fd8e1155b83 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#7  0x00007fd8e1151cf7 in EVP_CIPHER_CTX_cleanup () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#8  0x00007fd8e25fa3c3 in facebook::wdt::AESEncryptor::finishInternal(evp_cipher_ctx_st&, facebook::wdt::EncryptionType, std::string&) ()
   from /home/alpha/wdt/libwdt_min.so
#9  0x00007fd8e25fa550 in facebook::wdt::AESEncryptor::computeCurrentTag() () from /home/alpha/wdt/libwdt_min.so
#10 0x00007fd8e25f57ed in facebook::wdt::ClientSocket::computeCurEncryptionTag() () from /home/alpha/wdt/libwdt_min.so
#11 0x00007fd8e2647818 in facebook::wdt::SenderThread::sendOneByteSource(std::unique_ptr<facebook::wdt::ByteSource, std::default_delete<facebook::wdt::ByteSource> > const&, facebook::wdt::ErrorCode) () from /home/alpha/wdt/libwdt_min.so
#12 0x00007fd8e2647d1f in facebook::wdt::SenderThread::sendBlocks() () from /home/alpha/wdt/libwdt_min.so
#13 0x00007fd8e2649267 in facebook::wdt::SenderThread::start() () from /home/alpha/wdt/libwdt_min.so
#14 0x00007fd8e1aaec30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007fd8e1d38184 in start_thread (arg=0x7fd8decc8700) at pthread_create.c:312
#16 0x00007fd8e153c37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

**Comment by ldemailly** [comment]
Sorry for the delay, we've been busy.

Can you upgrade your openssl to 	2016-Sep-22 10:35:26 	openssl-1.0.1u
all earlier versions have serious security and other bugs

and confirm that fixes the crash?
thanks

**Comment by ldemailly** [comment]
please reopen if the upgrade didn't solve it or if you have any further problems
