### ISSUE TITLE
broken build because of gflags namespace change

### ISSUE THREAD

**Issue by ldemailly** [facebook/wdt#150]
see https://github.com/facebook/wdt/commit/84fd93c5e7dac9d33ea4bcd738fc252100d4c70c

document also need update
and as mentioned in comments there, I'm curious if lego oss build show the breakage internally as well

**Comment by dimitry-ishenko** [comment]
@ldemailly which version of gflags are you using?

On my system (Gentoo) I've had trouble compiling with gflags 2.1.1, which uses `gflags::` namespace. But it looks like in gflags 2.1.2 the namespace has changed to `google::` and it compiled w/o problems.

**Comment by ldemailly** [comment]
as referenced on the commit above, we build gflags from source using:
git clone https://github.com/schuhschuh/gflags.git
(mkdir gflags/build; cd gflags/build; cmake -DCMAKE_INSTALL_PREFIX=$HOME -DGFLAGS_NAMESPACE=google -DBUILD_SHARED_LIBS=on .. && make -j 4 && make install)

with this change we would need to remove the GFLAGS_NAMESPACE=google but that was necessary because that's I think how the binary (packaged) version of glog+gflag shipped

**Comment by ldemailly** [comment]
fixed now, thanks!
