### ISSUE TITLE
tail -f like behaviour

### ISSUE THREAD

**Issue by dimitry-ishenko** [facebook/wdt#151]
I'd like to send a large and growing file across the network. Is this something wdt is suitable for?

For example, I have an MPEG-TS video file being recorded. I'd like to transfer this file over the network as fast as possible. As the network bandwidth varies, it is possible that wdt will hit EOF and will need to wait for new data to arrive.

**Comment by ldemailly** [comment]
Yes you could but you would have to write code as it's not yet supported out of the box. A combination of our support for offsets/size and download resumption feature would be the building blocks for this.

**Comment by dimitry-ishenko** [comment]
@ldemailly I can take a stab at it, but will need some help finding the starting point. Would you be able to point me in the right direction?

**Comment by nikunjy** [comment]
This is an example of making a receiver with the download resumption
https://github.com/facebook/wdt/blob/master/wdtCmdLine.cpp#L305

And fileinfo, the name of the file, the offsets, etc can be set here.
https://github.com/facebook/wdt/blob/master/WdtTransferRequest.h#L177

**Comment by ldemailly** [comment]
Sorry for the delays, I was (and still am) traveling, and thanks Nikunj for stepping in.

You could possibly change the directory source queue to keep producing blocks - how would it end though ? how do you tell the difference between the file being slow to grow and the file has stopped growing ?

**Comment by dimitry-ishenko** [comment]
@ldemailly in this case it would only be interrupted by an external signal
