### ISSUE TITLE
Mandatory Parameters

### ISSUE THREAD

**Issue by NasrinJaleel93** [facebook/wdt#152]
What parameters of WdtTransferRequest should be mandatorily set on the receiver and sender end for a successful transfer? Any test code that can refer to?

Edit : Specifically sending and receiving machines in different networks?

**Comment by nikunjy** [comment]
This would be a good example 

https://github.com/facebook/wdt/blob/master/wdtCmdLine.cpp#L265

**Comment by NasrinJaleel93** [comment]
I don't clearly understand how the transfer between 2 machines in different networks would take place though. Do I need to give the IP or the fully qualified domain name as the hostname?

**Comment by ldemailly** [comment]
you need to give whichever address or name the receiver host is reachable under by the sender

typically it's the external IP of the receiver

if ports are blocked / there is no way to make a direct tcp connection, you can't use wdt as is; you'd have to use an intermediate host(s) that can talk to both machine as a proxy. We don't have an in memory proxy for wdt yet so you would need in that case to actually transfer to that intermediate host and then further transfer until you reach your final destination
