### ISSUE TITLE
Sending Buffers

### ISSUE THREAD

**Issue by NasrinJaleel93** [facebook/wdt#153]
From looking at the code, there seems to be no direct support for this. Any leads on what could be a good starting point to incorporate this feature?

**Comment by ldemailly** [comment]
The ByteSource interface is in theory how that would work but it'll take work as the DirectorySourceQueue is the only concrete queue implementation and makes FileByteSource concrete classes directly as well. but it would be a nice cleanup to make that vision a reality 

A practical short term workaround is to map your memory to /dev/shm files and send those using the existing code
