### ISSUE TITLE
wdt with 3 Mac computers with macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by topconnector** [facebook/wdt#160]
Here is my configuration: 3 Mac computers with macOS Sierra 10.12.5
Using mac AirPort for router.
1) iMac - wired LAN to AirPort- IP:10.0.1.9
2) MacBookPro - WiFi to AirPort-  IP:10.0.1.10
3) Mac-mini - WiFi to AirPort-  IP:10.0.1.7 

Executing commands from 1):
ssh-copy-id MyUserName@10.0.1.10 - OK
ssh-copy-id MyUserName@10.0.1.7 - OK
So there is no need for ssh password

This is OK:copy from MacBook
wdt  --encryption_type=none -directory /Users/MyName/Desktop/Test | ssh MyUserName@10.0.1.10 wdt --encryption_type=none -directory /Users/MyName/Documents/books -

I can see the files in Desktop/Test

This is NOT OK:copy from mac-mini
wdt  --encryption_type=none -directory /Users/MyName/Desktop/Test | ssh MyUserName@10.0.1.7 wdt --encryption_type=none -directory /Users/MyName/Documents/books -

I cannot see the files in Desktop/Test

Following:
https://github.com/facebook/wdt/blob/master/build/BUILD.md
CTEST_OUTPUT_ON_FAILURE=1 make test
on
1) iMac 
2) MacBookPro
all tests passed,
on 3) mac-mini 
CTEST_OUTPUT_ON_FAILURE=1 make test 
is returning the following:
(stopped because it took very long)
[make_test.txt](https://github.com/facebook/wdt/files/1073514/make_test.txt)

wdt --encryption_type=none -directory /Users/MyName/Desktop/Test | ssh  MyName@10.0.1.7 wdt --encryption_type=none -directory /Users/MyName/Documents/books -
log:
[wdt.txt](https://github.com/facebook/wdt/files/1073516/wdt.txt)

**Comment by ldemailly** [comment]
your sender never seem to connect 

can you run
```
wdt --encryption_type=none -directory /Users/MyName/Desktop/Test 2> /dev/null | ssh MyName@10.0.1.7 wdt --encryption_type=none -directory /Users/MyName/Documents/books -
```
(so we can see the sender side) and paste the output

**Comment by topconnector** [comment]
I got the following:
bash: wdt: command not found

**Comment by ldemailly** [comment]
so please put the wdt binary in the path on your third computer

**Comment by topconnector** [comment]
from 10.0.1.9
if I do:
ssh  MyName@10.0.1.7
and then
wdt
wdt is executed, so it can be found

what do you mean by "put the wdt binary in the path on your third computer"?

**Comment by ldemailly** [comment]
try putting the full path:

replace wdt by /usr/local/bin/wdt

**Comment by topconnector** [comment]
Thank you!
This seems to be working. Let me test it more. What about failed tests? And why I should explicitly enter the path?

**Comment by topconnector** [comment]
I tested now on a server in data center.
Got the following error:
E0613 23:59:21.342402 38752256 ClientSocket.cpp:55] wdt>	Failed getaddrinfo www.myserver.com , 59092 : 8 : nodename nor servname provided, or not known

**Comment by ldemailly** [comment]
try using `-hostname`

see comments and last line of sample in:

https://github.com/facebook/wdt/wiki/Getting-Started-with-the-WDT-command-line#everything-in-1-command

**Comment by topconnector** [comment]
I see
wdt -hostname fe80::202:c9ff:fe51:dd50 -directory destdir | ssh srchost wdt -directory srcdir -
how to get the ipv6 hostname?

**Comment by ldemailly** [comment]
it doesn't have to be ipv6 - this is just an example - it's whichever ip your receiver is reachable under from your source server

**Comment by topconnector** [comment]
I tested with ipv4 also:
wdt  -hostname aaa.bbb.ccc.ddd -directory ~/Desktop/MyDir | ssh  myusername@aa1.bb1.cc1.dd1 /usr/local/bin/wdt  -directory ~/Desktop/MyDir -

here are the logs:
[server.txt](https://github.com/facebook/wdt/files/1076182/server.txt)

**Comment by ldemailly** [comment]
2 issues:
```
W0614 16:37:21.541368 264495104 SenderThread.cpp:93] wdt>	Thread[7, port: 60887]  Connection took 2 attempt(s) and 6.07 seconds. port 60887
```

it's not normal it took 6 second to connect - what's your ping time between your 2 machines ?

And:

try with  --encryption_type=none first ?

if you have firewall setup you need to use ports that are open

also try with -num_ports=1 to simplify at first (you get better throughput with more obviously)

**Comment by topconnector** [comment]
ping time to this server is 0.544ms

**Comment by ldemailly** [comment]
can u send the log with 1 port and no encryption 

also can you find out (use `nc` (netcat) for instance) why a tcp connection takes 6s ?

**Comment by topconnector** [comment]
could you please send me example about how to use nc (netcat) to check the tcp connection?

**Comment by ldemailly** [comment]
You still have

E0615 20:41:24.104460 222154752 ClientSocket.cpp:55] wdt>	Failed getaddrinfo hatc1.melissadata.com , 63497 : 8 : nodename nor servname provided, or not known

please use a working -hostname

for netcat you can do nc --help or google examples

**Comment by ldemailly** [comment]
@topconnector can you close the issue if it's resolved? thanks!
