### ISSUE TITLE
appears the following error，  Who can help me?

### ISSUE THREAD

**Issue by shanwu888** [facebook/wdt#164]
/usr/local/src/wdt/../folly/folly/Portability.h:33: error: expected constructor, destructor, or type conversion before ‘bool’
/usr/local/src/wdt/../folly/folly/Portability.h:39: error: expected unqualified-id before ‘using’
/usr/local/src/wdt/../folly/folly/Portability.h:43: error: expected template-name before ‘<’ token
/usr/local/src/wdt/../folly/folly/Portability.h:43: error: expected ‘{’ before ‘<’ token
/usr/local/src/wdt/../folly/folly/Portability.h:43: error: expected unqualified-id before ‘<’ token
/usr/local/src/wdt/../folly/folly/Portability.h:49: error: expected unqualified-id before ‘using’
/usr/local/src/wdt/../folly/folly/Portability.h:51: error: expected nested-name-specifier before ‘max_basic_alignment’
/usr/local/src/wdt/../folly/folly/Portability.h:51: error: ‘max_basic_alignment’ has not been declared
/usr/local/src/wdt/../folly/folly/Portability.h:51: error: expected ‘;’ before ‘=’ token
/usr/local/src/wdt/../folly/folly/Portability.h:51: error: expected unqualified-id before ‘=’ token
/usr/local/src/wdt/../folly/folly/Portability.h:68: error: ‘constexpr’ does not name a type
/usr/local/src/wdt/../folly/folly/Portability.h:100: error: expected initializer before ‘max_align_t’
/usr/local/src/wdt/../folly/folly/Portability.h:184: error: expected constructor, destructor, or type conversion before ‘bool’
/usr/local/src/wdt/../folly/folly/Portability.h:185: error: expected constructor, destructor, or type conversion before ‘bool’
/usr/local/src/wdt/../folly/folly/Portability.h:186: error: expected constructor, destructor, or type conversion before ‘bool’
/usr/local/src/wdt/../folly/folly/Portability.h:194: error: expected constructor, destructor, or type conversion before ‘bool’
/usr/local/src/wdt/../folly/folly/Portability.h:200: error: expected constructor, destructor, or type conversion before ‘bool’
/usr/local/src/wdt/../folly/folly/Portability.h:312: error: expected constructor, destructor, or type conversion before ‘auto’
/usr/local/src/wdt/../folly/folly/Portability.h:328: error: expected constructor, destructor, or type conversion before ‘auto’
/usr/local/src/wdt/../folly/folly/Portability.h:330: error: expected constructor, destructor, or type conversion before ‘auto’
/usr/local/src/wdt/../folly/folly/Portability.h:393: error: expected constructor, destructor, or type conversion before ‘auto’
/usr/local/src/wdt/../folly/folly/Portability.h:397: error: expected constructor, destructor, or type conversion before ‘auto’
/usr/local/src/wdt/../folly/folly/Portability.h:406: error: expected constructor, destructor, or type conversion before ‘auto’
/usr/local/src/wdt/../folly/folly/Portability.h:407: error: expected constructor, destructor, or type conversion before ‘auto’
make[2]: *** [CMakeFiles/folly4wdt.dir/usr/local/src/folly/folly/detail/Crc32cDetail.cpp.o] Error 1
make[1]: *** [CMakeFiles/folly4wdt.dir/all] Error 2

**Comment by ldemailly** [comment]
it would be useful if you indicated which OS you are trying this on ?
Also please paste the full output of cmake before the first error

**Comment by ldemailly** [comment]
is it the same as #163 ? you seem to have an old cmake ? possibly old c++ compiler too ?

**Comment by shanwu888** [comment]
os is centos

**Comment by davide125** [comment]
Please reopen if this still repros
