### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [facebook/wdt#18]
A few parameters are passed to [CMake commands in your build script](https://github.com/facebook/wdt/blob/2e60ce04c982794ca76b1a22bcc1c2413747ac59/CMakeLists.txt#L49 "Update candidate") without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by ldemailly** [comment]
thanks, can you give an example ?



—

**Comment by elfring** [comment]
Update candidates:
* ${CMAKE_CURRENT_SOURCE_DIR}/deps/folly
* ${GLOG_INCLUDE_DIR}
* ${SOURCE_DIR}/include

**Comment by ldemailly** [comment]
I meant an example of error one would get with the current cmake - will look at the wiki (proper quoting is important in shell scrips - and we do have that issue in ours - but cmake isnt running commands per so I am curious)

**Comment by elfring** [comment]
Do you get any further ideas from [other bug reports](http://www.cmake.org/Bug/view.php?id=15076 "CMake does not support source/build trees with ';' in the path.") and corresponding update suggestions?

**Comment by ldemailly** [comment]
Ok, I'm adding "" around variable references but to be honest I'm not sure supporting ";" inside pathname is really important - is it ?

Looking forward to your testing of the upcoming updated Cmake

**Comment by elfring** [comment]
Thanks for [your improvement of a build script](https://github.com/facebook/wdt/commit/5c0c26bb27a56640dc4d9761ac9bc54ce93433de#diff-af3b638bc2a3e6c650974192a53c7291L22 "More quoting").
