### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by jamie-arcc** [facebook/wdt#186]
Are the maintainers still active with this project?  I noticed there hasn't been a release in nearly three years and that there are a lot of old, unresolved issues

**Comment by ldemailly** [comment]
The open issues are mostly ideas for possible improvements and afaik there are no serious bugs and wdt has been used successfully for years in production

So yes it is alive, just not actively developed that I know of

**Comment by davide125** [comment]
It's actively used within FB, but not actively developed at the time being.
