### ISSUE TITLE
Option to compile wdt against libfolly rather than building libfolly4wdt subset

### ISSUE THREAD

**Issue by hjmallon** [facebook/wdt#194]
Having a subset of folly build with wdt makes packaging the library and utils difficult with package managers. Is it possible / supported to build against a full version of folly?

Relevant to https://github.com/Homebrew/homebrew-core/pull/39345

TITLE WAS: "Could folly (complete) be used rather than folly4wdt?"

**Comment by hjmallon** [comment]
I have been able to pass all tests with a patch as follows and folly installed from brew

[patch.txt](https://github.com/facebook/wdt/files/3126821/patch.txt)

**Comment by ldemailly** [comment]
The reason for the crurent setup is that full folly is both huge and hard to build and wdt tried to have minimal dependencies. So it would make sense to have the « option » to use a prebuilt full folly but it shouldn’t be the only way nor the default

**Comment by hjmallon** [comment]
Having an option would be perfect.

**Comment by ldemailly** [comment]
I guess one should add code to detect if folly is already installed

**Comment by hjmallon** [comment]
Option in CMake for build against full folly is here https://github.com/hjmallon/wdt/commit/ec6bbad26527c34f52edae4adcbb5ada0c2b8ad3

**Comment by zbeekman** [comment]
A default option set to "ON" that could be set to "OFF" would be sufficient to get it into homebrew. I agree that the more suitable way to handle this, in the long run, is through CMake system introspection & `find_package()` etc.

If you can create a new release with an option to turn off vendored folly (following an approach like the one suggested by @hjmallon) then that would increase the chances that it can be accepted into Homebrew, which in turn helps increase adoption and visibility...
