### ISSUE TITLE
Error about libfolly4wdt.so: undefined reference to `cplus_demangle_v3_callback'

### ISSUE THREAD

**Issue by xhqnarr** [facebook/wdt#198]
ubuntu 16.04    gcc 5.4  folly 2016.12.19.00

error info :

 ubuntu@ubuntu:~/src/wdt$ make

[ 68%] Linking CXX executable _bin/wdt/protocol_test
CMakeFiles/protocol_test.dir/test/ProtocolTest.cpp.o: In function `facebook::wdt::Protocol_encodeVarI64C_Test::TestBody()':
ProtocolTest.cpp:(.text+0x33a): undefined reference to `testing::internal::DeathTest::Create(char const*, testing::Matcher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, char const*, int, testing::internal::DeathTest**)'
collect2: error: ld returned 1 exit status
CMakeFiles/protocol_test.dir/build.make:104: recipe for target '_bin/wdt/protocol_test' failed
make[2]: *** [_bin/wdt/protocol_test] Error 1
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/protocol_test.dir/all' failed
make[1]: *** [CMakeFiles/protocol_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

thanks!

**Comment by majoros** [comment]
try using gtest 1.7.0, I think that's how resolved this issue. 

https://github.com/google/googletest/releases/tag/release-1.7.0

**Comment by RoshanPAN** [comment]
I'm using folly::Random::rand32() in my code and
with gtest 1.8 I still have this issue during build. @majoros 
```
/usr/bin/cmake --build /tmp/tmp.eDsqTsGXsB/cmake-build-debug-local-container --target docker_clion_dev -- -j 6
[ 50%] Linking CXX executable docker_clion_dev
/usr/local/lib/libfolly.a(Demangle.cpp.o): In function `folly::detail::cplus_demangle_v3_callback_wrapper(char const*, void (*)(char const*, unsigned long, void*), void*)':
/usr/src/folly/folly-2019.09.23.00/folly/detail/Demangle.cpp:38: undefined reference to `cplus_demangle_v3_callback'
collect2: error: ld returned 1 exit status
test_libraries/CMakeFiles/docker_clion_dev.dir/build.make:94: recipe for target 'test_libraries/docker_clion_dev' failed
make[3]: *** [test_libraries/docker_clion_dev] Error 1
CMakeFiles/Makefile2:85: recipe for target 'test_libraries/CMakeFiles/docker_clion_dev.dir/all' failed
make[2]: *** [test_libraries/CMakeFiles/docker_clion_dev.dir/all] Error 2
CMakeFiles/Makefile2:97: recipe for target 'test_libraries/CMakeFiles/docker_clion_dev.dir/rule' failed
make[1]: *** [test_libraries/CMakeFiles/docker_clion_dev.dir/rule] Error 2
Makefile:164: recipe for target 'docker_clion_dev' failed
make: *** [docker_clion_dev] Error 2
```
