### ISSUE TITLE
build wdt_url_test failed 

### ISSUE THREAD

**Issue by bolunfeng** [facebook/wdt#212]
[ 87%] Building CXX object CMakeFiles/wdt_url_test.dir/test/WdtUrlTest.cpp.o
In file included from /home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest.h:387,
                 from /home/fbl/workspace/wdt/test/EncryptionTest.cpp:4:
/home/fbl/workspace/wdt/test/EncryptionTest.cpp: In function ‘void facebook::wdt::testEncryption(facebook::wdt::EncryptionType, const string&)’:
**/home/fbl/workspace/wdt/test/EncryptionTest.cpp:76:57: error: no matching function for call to ‘find(std::vector<std::__cxx11::basic_string<char> >::iterator, std::vector<std::__cxx11::basic_string<char> >::iterator, std::string&)’**
   76 |     EXPECT_EQ(std::find(tags.begin(), tags.end(), curTag), tags.end());
      |                                                         ^
/home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   77 |   if (const ::testing::AssertionResult gtest_ar = (expression)) \
      |                                                    ^~~~~~~~~~
/home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest_pred_impl.h:164:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
  164 |   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
      |   ^~~~~~~~~~~~~~~~~~~
/home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest.h:2040:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
 2040 |   EXPECT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
      |   ^~~~~~~~~~~~~~~~~~~
/home/fbl/workspace/wdt/test/EncryptionTest.cpp:76:5: note: in expansion of macro ‘EXPECT_EQ’
   76 |     EXPECT_EQ(std::find(tags.begin(), tags.end(), curTag), tags.end());
      |     ^~~~~~~~~
In file included from /usr/include/c++/9/bits/locale_facets.h:48,
                 from /usr/include/c++/9/bits/basic_ios.h:37,
                 from /usr/include/c++/9/ios:44,
                 from /usr/include/c++/9/ostream:38,
                 from /usr/include/glog/logging.h:43,
                 from /home/fbl/workspace/wdt/../wdt/ErrorCodes.h:12,
                 from /home/fbl/workspace/wdt/../wdt/util/EncryptionUtils.h:13,
                 from /home/fbl/workspace/wdt/test/EncryptionTest.cpp:1:
/usr/include/c++/9/bits/streambuf_iterator.h:373:5: note: candidate: ‘template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)’
  373 |     find(istreambuf_iterator<_CharT> __first,
      |     ^~~~
/usr/include/c++/9/bits/streambuf_iterator.h:373:5: note:   template argument deduction/substitution failed:
In file included from /home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest.h:387,
                 from /home/fbl/workspace/wdt/test/EncryptionTest.cpp:4:
/home/fbl/workspace/wdt/test/EncryptionTest.cpp:76:57: note:   ‘__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
   76 |     EXPECT_EQ(std::find(tags.begin(), tags.end(), curTag), tags.end());
      |                                                         ^
/home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest_pred_impl.h:77:52: note: in definition of macro ‘GTEST_ASSERT_’
   77 |   if (const ::testing::AssertionResult gtest_ar = (expression)) \
      |                                                    ^~~~~~~~~~
/home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest_pred_impl.h:164:3: note: in expansion of macro ‘GTEST_PRED_FORMAT2_’
  164 |   GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_NONFATAL_FAILURE_)
      |   ^~~~~~~~~~~~~~~~~~~
/home/fbl/workspace/wdt/gtest/src/gtest/googletest/include/gtest/gtest.h:2040:3: note: in expansion of macro ‘EXPECT_PRED_FORMAT2’
 2040 |   EXPECT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
      |   ^~~~~~~~~~~~~~~~~~~
/home/fbl/workspace/wdt/test/EncryptionTest.cpp:76:5: note: in expansion of macro ‘EXPECT_EQ’
   76 |     EXPECT_EQ(std::find(tags.begin(), tags.end(), curTag), tags.end());
      |     ^~~~~~~~~
make[2]: *** [CMakeFiles/encryption_test.dir/build.make:63：CMakeFiles/encryption_test.dir/test/EncryptionTest.cpp.o]

**Comment by JustinTimperio** [comment]
Sadly Facebook has basically abandoned community support for this. I wrote a tool called [warp-cli](https://github.com/JustinTimperio/warp-cli) which also includes a [shell install script](https://github.com/JustinTimperio/warp-cli/blob/master/build/install.sh) that uses a locked version of FOLLY and WDT.

You can install it with `curl https://raw.githubusercontent.com/JustinTimperio/warp-cli/master/build/install.sh | sudo bash`

**Comment by davide125** [comment]
@bolunfeng, can you share a few more details on your environment so I can try to repro the failure you're seeing here?

@JustinTimperio, Facebook employee here; I'm trying to get this back in better shape and will triage open issues and PRs as time allows in the coming weeks.

**Comment by JustinTimperio** [comment]
@davide125 Glad to hear that this may repo may actually get some love. I have been considering abandoning and archiving my project because of how bad this repo has become. I opened #199 over a year ago and the community was able to patch it, yet I still need to [hackly patch the cmake list ](https://github.com/JustinTimperio/warp-cli/blob/b7d8ff6194690514a87fc20e2ec28640e683706b/build/install.sh#L89) during every install because no one has bothered to merge this change.

**Comment by bolunfeng** [comment]
@davide125    I updated the latest version of the code and the problem has been resolved. Thank you very much. I have questions in the future, can I ask you directly by email or other means?

**Comment by davide125** [comment]
Feel free to file issues here for bugs, or to ask in the gitter chat linked in the README for questions.

To set expectations: wdt is widely used at Facebook, but it's mostly "done" and is not being actively developed beyond the occasional bug fix; my goal here is to get pending PRs merged, triage the issues, sort out the build so it works (hopefully) reliably, and ideally get the CI moved over to github actions so we don't regress it in the future. The main catalyst for this an ongoing effort to get wdt [packaged](https://bugzilla.redhat.com/show_bug.cgi?id=1891040) in Fedora that I'm trying to help with.
