### ISSUE TITLE
build failed, help me, please

### ISSUE THREAD

**Issue by Shuo-Jia** [facebook/wdt#222]
## gcc version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 ## cmake version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

## error message

![选区_999(153)](https://user-images.githubusercontent.com/23136769/129835320-0ef8287b-e85d-4ddc-8ece-3af43b4df11a.png)

**Comment by Shuo-Jia** [comment]
@ldemailly Could you help me resolve the problem? I have test it multi-time, it still failed

**Comment by ldemailly** [comment]
Sorrt, I have not built wdt in years. Maybe put the full text out rather than a screenshot? and google the error?

I would guess though that your gcc/g++ is too old

**Comment by Shuo-Jia** [comment]
> Sorry, I have not built wdt in years. Maybe put the full text out rather than a screenshot? and google the error?
> 
> I would guess though that your gcc/g++ is too old

The gcc/g++ has been 7.5. I guess it is compatibility for  master branch of `wdt` and `folly`, which the wdt only update in 2016, but the folly has been 2021, I try use the version of them in 2017, the error is disappeared，but appear other error.

I can't find the match version for them, so I want to know which version is matched

**Comment by SiminBadri** [comment]
I tried to build WDT but it failed with the error @Shuo-Jia mentioned. I solved it temporarily until it's fixed by contributors. 

In line 206 from file wdt/Receiver.h, change
`  std::atomic<std::chrono::time_point<Clock>> startTime_;
`
to
`  std::atomic<std::chrono::time_point<Clock>> startTime_{Clock::now()};
`
.

I hope it helps you resolve your problem.

**Comment by Shuo-Jia** [comment]
@SiminBadri Thanks a lot! and I found a rep which offer one scripts to resolve the verson match problem: https://github.com/JustinTimperio/warp-cli, maybe you can follow it

**Comment by Shuo-Jia** [comment]
> @SiminBadri Thanks a lot! and I found a rep which offer a script to resolve the verson match problem: https://github.com/JustinTimperio/warp-cli, maybe you can follow it

resolved
