### ISSUE TITLE
Cant transfer data[need help]

### ISSUE THREAD

**Issue by Xiang-cd** [facebook/wdt#234]
on src host:
ssh dst  wdt --transfer_id=1234 -directory /mnt/recivie  | wdt --encryption_type=none --transfer_id=1234 -directory  ./send -destination <ipv4addrofdst> --ipv4
but always fail with
connect did not succeed on  <ipv4addrofdst> 22363 : Connection refused

how could I do?

**Comment by Xiang-cd** [comment]
Failed getaddrinfo xiangxiaoyudeMacBook-Pro.local , 54263 : -2 
i dont now how the URL were made, xiangxiaoyudeMacBook is certainly an invalid severname

**Comment by daniel-ai2** [comment]
Were you ever able to get it to connect? I am running into the exact same issue.

**Comment by ldemailly** [comment]
pass the right `-hostname` if the default one isn't correct?

**Comment by Xiang-cd** [comment]
thanks~
