### ISSUE TITLE
IP Connection Fails when given an Ipv4 instead of a name as input and --ipv6 is true (default)

### ISSUE THREAD

**Issue by oblogic7** [facebook/wdt#31]
I get the following error when trying to connect to the receiver via IP address.

```E0729 17:08:27.555832 26484736 ClientSocket.cpp:49] Failed getaddrinfo 192.168.2.2 , 22363 : 8 : nodename nor servname provided, or not known```

I thought this was a DNS lookup issue, but that doesn't seem to be the case.  Adding the address to my host file and using the specified hostname resulted in the same error.

Sender is OS X 10.9.5
Receiver is 10.10.2

Direct connection via ethernet.

**Comment by ldemailly** [comment]
Hi Matt,

First thanks a lot for trying out WDT and successfully building it (was that ok?)

if you are using ipv4 instead of a name or ipv6 you need to say --ipv4

By default wdt tries to obtain an ipv6 address

I will add this to the faq

**Comment by ldemailly** [comment]
Added https://github.com/facebook/wdt/wiki/FAQ#trying-to-use-directly-an-ipv4-address

Please confirm this resolved your issue and also let us know how are your test going

**Comment by oblogic7** [comment]
Thanks for the clarification.  I did notice that it was attempting to use an IPv6 address when I used the actual hostname for the machine (not the host file entry), but that wasn't connecting for some reason either.

The IPv6 error was `I0729 19:38:37.095441 91713536 ClientSocket.cpp:78] Error connecting on fe80::6a5b:35ff:fec8:70c1%bridge100 22363: No route to host [65]`

My machines are directly connected, so it is a simple setup, but may be something on my end.  Let me know if that error gives any direction.

The build was fairly easy, although there were some issues with the directions in BUILD.txt.  I may issue a pull request and make corrections as needed for OS X.

**Comment by oblogic7** [comment]
Just tried the --ipv4 flag and got the following error.

`E0729 19:38:37.516623 231915520 Receiver.cpp:794] Receiver and sender id mismatch 442584604 1284356090`

I see that the sender generates an id, but what about the receiver?  Do I need to do something special to get them to match?

**Comment by ldemailly** [comment]
Matt for your ipv6 error I would suggest you first try to confirm
'''
ping fe80::6a5b:35ff:fec8:70c1%bridge100
'''
works, the % part I'm not familiar with/seems odd btw

if you can ssh or ping or telnet to your host you should be able to wdt to it, using the same name or IP - if that's not the case I'd love to know

I'd love to know what was off in the BUILDS.txt beside probably the location of the folly checkout which I updated but having pushed here yet

The transfer_id needs to match between sender and receiver, the easiest way to achieve that is to start the receiver first and take the url it prints to stdout and use that for the sender
This is what the wdt_e2e_simple_test.sh does (which btw doesn't pass on the mac because of a symlink issue but I'll be fixing that - if you don't use --follow_symlink that bug won't affect you)

An alternative is you just set --transfer_id=XYZ on both command lines

**Comment by oblogic7** [comment]
There were a few steps missing from the directions and a few things were out of order.  I would have to go back through to remember specifics.

Here are the results of my first test.

```I0729 20:27:09.171581 2009608976 Sender.cpp:330] Total sender time = 327.304 seconds (0.00230432 dirTime). Transfer summary : Transfer status = OK. Number of files transferred = 56. Data Mbytes = 21232.6. Header kBytes = 111.766 (0.00051405% overhead). Total bytes = 22264110155. Wasted bytes due to failure = 0 (0% overhead).
Total sender throughput = 64.8716 Mbytes/sec (64.872 Mbytes/sec pure transf rate)```

Hardware setup for testing was as follows.

iMac w/ Internal 7200RPM HDD -> 1000Mbit wired network bridge -> Macbook Pro -> Thunderboldt connected 7200RPM external HDD

**Comment by ldemailly** [comment]
I'm going to change the default as ipv6 for the general case is still a bit early and will cause people to stumble unnecessary

Thanks in advance for the update to BUILDS.txt - though I'm also working to get travis ci and that will contain definitive steps

**Comment by ldemailly** [comment]
We haven't yet tuned/optimized for disk, mostly for flash read/write - you can try to change --num_ports (which also changes the reader/writers) to see if you get better throughput but 65Mb sounds about right for a normal hard drive - though maybe you should be able to squeeze a bit more than that

**Comment by oblogic7** [comment]
Pull request #34 submitted for BUILD.txt updates.

**Comment by ldemailly** [comment]
thanks ! will close this one (I fixed/changed the default value so you shouldn't need the -ipv6=false workaround even)
