### ISSUE TITLE
connection error should indicate the ip it tried to connect to

### ISSUE THREAD

**Issue by ldemailly** [facebook/wdt#37]
W0730 16:14:53.266710 2300510 ClientSocket.cpp:126] connect did not succeed : Connection refused
E0730 16:14:53.266685 2300509 Sender.cpp:483] Unable to connect to devbig074.prn2.facebook.com 22358 despite 20 retries in 0.956401 seconds.

we should also indicate the addr used

**Comment by DevarshDesai** [comment]
Hi Laurent,

It is my understanding that anything that starts with FD in the IPv6 address corresponds to the (internal) network (Unicast) address. The change in the associated pull request adds the information associated with the fd_ member variable from the Socket Client class to the error message arising from the Sender's connectToReceiver method. I inferred after looking through the class files that this is the information you're looking for, however:

1) This is my first contribution to open source :O)
2)  I'm primarily a java developer

Please let me know if you're looking for more specific information to be displayed within the error messages from the Client Socket and Sender classes.

Thank you for your time,
Warm Regards,
Devarsh Desai

**Comment by ldemailly** [comment]
Hi Dervash, 
Thanks a lot for looking at wdt and contributing !

the fd is just a the index of the file descriptor and not realted to any ip though so your proposed change wouldn't do what I meant here - we forgot to close that issue which was resolved by Uddipta's latest commit

**Comment by DevarshDesai** [comment]
Hey Laurent,

Thank YOU for taking the time to explain aspects of the Client Socket class, I sincerely appreciate it.

I'll continue looking out for interesting issues!

Thank you for your time,
Warm Regards,
Devarsh Desai
