### ISSUE TITLE
how to do a local transfer test?

### ISSUE THREAD

**Issue by nzomkxia** [facebook/wdt#39]
receiver side:  wdt -directory wdtData/
sender side : wdt -directory /usr/bin/ -destination localhost

can't get the content transfered frome /usr/bin/ to wdtData, the receiver and sender run on a same mac book.

**Comment by uddipta** [comment]
Command lines you mentioned should work. Can you provide logs of both sides?

**Comment by ldemailly** [comment]
transferid is missing



—

**Comment by ldemailly** [comment]
you can also copy paste the url generated by the receiver and give it to the sender as -connection_url - it will contain a unique transfer_id (id parameter)

please reopen if you still have any problem
