### ISSUE TITLE
Make Wdt URI more awesome

### ISSUE THREAD

**Issue by nikunjy** [facebook/wdt#47]
Couple of things can be added to WdtUri 

1. Short URL should have the capability to shorten ports if all ports are continous into numports and hostName:startPort

2. If hostname is empty or ports are empty, try to build from wdt options

3. ErrorCode could be sent as part of URL

**Comment by ldemailly** [comment]
mostly done in https://github.com/facebook/wdt/commit/a4f851229040de41d6198467065d216a73c584c6
