### ISSUE TITLE
Destination host is transmitting as much data as receiving

### ISSUE THREAD

**Issue by yonas** [facebook/wdt#53]
I just compiled wdt today and, although it transfers data quickly, I noticed that the destination host was transmitting exactly the same amount of data as it was receiving.

I'm using Gnome's System Monitor to monitor the network traffic. Both sender and receiver hosts were running wdt from within a Docker container (Ubuntu 14.04.3 LTS).

**Comment by yonas** [comment]
Sorry, I just realized this is caused by Docker transferring the data to the container.

**Comment by ldemailly** [comment]
Glad you are trying out WDT - I hope it works well for your needs and don't hesitate to suggest improvements or report any issue
