### ISSUE TITLE
centos build wdt failed

### ISSUE THREAD

**Issue by zjy7895123** [facebook/wdt#66]
[root@localhost ~]# uname -a
Linux localhost.localdomain 2.6.18-308.el5 #1 SMP Tue Feb 21 20:06:06 EST 2012 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# gcc --version
gcc (GCC) 4.9.0
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@localhost ~]# cmake --version
cmake version 3.2.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

My machine is centos.When i build wdt,the error occure: error like this:cc1plus: error: unrecognized command line option "-msse4.2"

gcc is 4.9.0
cmake is 3.3.0
and other package like gflags glog...I have builded by source.
Are there any other points need to pay attention to?

**Comment by ldemailly** [comment]
I noticed you closed the issue soon after opening - what was the solution ?

if you have problems in the future add the full output of your cmake command

**Comment by zjy7895123** [comment]
Just because I have two versions of gcc, when i make, it use old version.
