### ISSUE TITLE
Fail to transfer data.

### ISSUE THREAD

**Issue by nxtreaming** [facebook/wdt#67]
I fail to transfer any data between two host( one is located in USA West, another is in China).
the wdt always reports:  Receiver and sender id mismatch xxxxx yyyyyy

The following is the log of wdt receiver:

root@i-19uz5u6n:/main_disk/test_data# wdt -directory /main_disk/test_data/
I0905 19:08:55.293244  6624 WdtFlags.cpp:64] Running WDT 1.16.1508311 p 16
I0905 19:08:55.293895  6624 Receiver.cpp:126] WDT Receiver 1.16.1508311 p 16
I0905 19:08:55.294070  6624 WdtBase.cpp:304] Generated a transfer id 708577588
I0905 19:08:55.294128  6624 WdtBase.cpp:272] using wdt protocol version 16
I0905 19:08:55.294659  6624 Receiver.cpp:160] Registered 8 sockets
I0905 19:08:55.294714  6624 Receiver.cpp:172] Transfer id 708577588
I0905 19:08:55.294776  6624 wdtCmdLine.cpp:168] Starting receiver with connection url 
wdt://i-19uz5u6n?ports=22356,22357,22358,22359,22360,22361,22362,22363&protocol=16&id=708577588
I0905 19:08:55.294911  6624 wdtCmdLine.cpp:83] Setting up abort 0 seconds.
I0905 19:08:55.294942  6624 Receiver.cpp:419] Starting (receiving) server on ports [ 22356 22357 22358 22359 22360 22361 22362 22363 ] Target dir : /main_disk/test_data/
I0905 19:08:55.294976  6624 FileCreator.cpp:222] dir already exists /
I0905 19:08:55.294998  6624 FileCreator.cpp:222] dir already exists /main_disk/
I0905 19:08:55.295013  6624 FileCreator.cpp:222] dir already exists /main_disk/test_data/
I0905 19:08:55.295054  6624 WdtBase.cpp:292] Throttling not enabled
I0905 19:08:55.298210  6633 Receiver.cpp:376] Progress reporter updating every 20 ms
I0905 19:09:18.116607  6628 Receiver.cpp:523] New transfer started 1
E0905 19:09:18.116955  6628 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.116976  6628 Receiver.cpp:1255] Thread[3, port: 22359]  entered SEND_ABORT_CMD state 
I0905 19:09:18.117035  6628 Receiver.cpp:1313] Thread[3, port: 22359]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.117059  6628 Receiver.cpp:110] Adding global checkpoint 22359 0 0
E0905 19:09:18.126565  6626 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.126641  6626 Receiver.cpp:1255] Thread[1, port: 22357]  entered SEND_ABORT_CMD state 
I0905 19:09:18.126684  6626 Receiver.cpp:1313] Thread[1, port: 22357]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.126704  6626 Receiver.cpp:110] Adding global checkpoint 22357 0 0
E0905 19:09:18.129009  6629 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.129056  6629 Receiver.cpp:1255] Thread[4, port: 22360]  entered SEND_ABORT_CMD state 
I0905 19:09:18.129114  6629 Receiver.cpp:1313] Thread[4, port: 22360]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.129143  6629 Receiver.cpp:110] Adding global checkpoint 22360 0 0
E0905 19:09:18.131338  6632 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.131372  6632 Receiver.cpp:1255] Thread[7, port: 22363]  entered SEND_ABORT_CMD state 
I0905 19:09:18.131412  6632 Receiver.cpp:1313] Thread[7, port: 22363]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.131431  6632 Receiver.cpp:110] Adding global checkpoint 22363 0 0
E0905 19:09:18.134858  6631 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.134884  6631 Receiver.cpp:1255] Thread[6, port: 22362]  entered SEND_ABORT_CMD state 
I0905 19:09:18.134917  6631 Receiver.cpp:1313] Thread[6, port: 22362]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.134933  6631 Receiver.cpp:110] Adding global checkpoint 22362 0 0
I0905 19:09:18.136365  6630 Receiver.cpp:628] Thread[5, port: 22361]  entered ACCEPT_WITH_TIMEOUT state 
I0905 19:09:18.136404  6627 Receiver.cpp:628] Thread[2, port: 22358]  entered ACCEPT_WITH_TIMEOUT state 
E0905 19:09:18.143194  6630 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.143245  6630 Receiver.cpp:1255] Thread[5, port: 22361]  entered SEND_ABORT_CMD state 
I0905 19:09:18.143299  6630 Receiver.cpp:1313] Thread[5, port: 22361]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.143329  6630 Receiver.cpp:110] Adding global checkpoint 22361 0 0
E0905 19:09:18.385826  6627 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.385893  6627 Receiver.cpp:1255] Thread[2, port: 22358]  entered SEND_ABORT_CMD state 
I0905 19:09:18.385964  6627 Receiver.cpp:1313] Thread[2, port: 22358]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.385990  6627 Receiver.cpp:110] Adding global checkpoint 22358 0 0
E0905 19:09:18.792495  6625 Receiver.cpp:815] Receiver and sender id mismatch 736683926 708577588
I0905 19:09:18.792554  6625 Receiver.cpp:1255] Thread[0, port: 22356]  entered SEND_ABORT_CMD state 
I0905 19:09:18.792611  6625 Receiver.cpp:1313] Thread[0, port: 22356]  entered WAIT_FOR_FINISH_WITH_THREAD_ERROR state 
I0905 19:09:18.792634  6625 Receiver.cpp:110] Adding global checkpoint 22356 0 0
I0905 19:09:18.792659  6625 Receiver.cpp:475] Received done for all threads. Transfer session 1 finished
W0905 19:09:18.793324  6631 Receiver.cpp:1425] Last thread finished. Duration of the transfer 0.676722
W0905 19:09:18.793570  6624 Receiver.cpp:277] WDT receiver's transfer has been finished
I0905 19:09:18.793588  6624 Receiver.cpp:278] Transfer status (local) = ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.109375 (100% overhead). Total bytes = 112. Wasted bytes due to failure = 0 (100% overhead).
root@i-19uz5u6n:/main_disk/test_data# 

------------------------------------------------------
The following is the log of wdt server(sender) 
root@localhost:/relay/dev# wdt -directory /relay/dev/test_data/ -destination rtmp.imbatv.cn
I0905 11:09:18.096493   576 WdtFlags.cpp:64] Running WDT 1.16.1508311 p 16
I0905 11:09:18.097306   576 Sender.cpp:155] WDT Sender 1.16.1508311 p 16
I0905 11:09:18.097429   576 DirectorySourceQueue.cpp:116] Root dir now /relay/dev/test_data/
I0905 11:09:18.097575   576 WdtBase.cpp:304] Generated a transfer id 736683926
I0905 11:09:18.097633   576 WdtBase.cpp:272] using wdt protocol version 16
I0905 11:09:18.097725   576 wdtCmdLine.cpp:212] Starting sender with details wdt://rtmp.imbatv.cn?ports=22356,22357,22358,22359,22360,22361,22362,22363&protocol=16&dir=/relay/dev/test_data/&id=736683926
I0905 11:09:18.097775   576 wdtCmdLine.cpp:83] Setting up abort 0 seconds.
I0905 11:09:18.097811   576 Sender.cpp:376] Client (sending) to rtmp.imbatv.cn, Using ports [ 22356 22357 22358 22359 22360 22361 22362 22363 ]
I0905 11:09:18.097975   576 WdtBase.cpp:292] Throttling not enabled
I0905 11:09:18.098412   577 DirectorySourceQueue.cpp:214] Exploring root dir /relay/dev/test_data/ include_pattern :  exclude_pattern :  prune_dir_pattern : 
I0905 11:09:18.098726   577 DirectorySourceQueue.cpp:362] Number of files explored: 1, errors: false
I0905 11:09:18.102386   587 Sender.cpp:1300] Progress reporter tracking every 20 ms
[                                                 ] 0% 0.0 0.0 Mbytes/s  I0905 11:09:18.318181   582 Sender.cpp:507] Connection took 1 attempt(s) and 0.218243 seconds. port 22359
I0905 11:09:18.324580   586 Sender.cpp:507] Connection took 1 attempt(s) and 0.222995 seconds. port 22363
[                                                 ] 0% 0.0 0.0 Mbytes/s  I0905 11:09:18.324606   585 Sender.cpp:507] Connection took 1 attempt(s) and 0.2235 seconds. port 22362
I0905 11:09:18.325098   579 Sender.cpp:507] Connection took 1 attempt(s) and 0.226289 seconds. port 22356
I0905 11:09:18.325328   584 Sender.cpp:507] Connection took 1 attempt(s) and 0.224259 seconds. port 22361
I0905 11:09:18.326326   580 Sender.cpp:507] Connection took 1 attempt(s) and 0.227023 seconds. port 22357
I0905 11:09:18.326859   583 Sender.cpp:507] Connection took 1 attempt(s) and 0.226104 seconds. port 22360
I0905 11:09:18.332675   581 Sender.cpp:507] Connection took 1 attempt(s) and 0.233638 seconds. port 22358
[                                                 ] 0% 0.0 0.0 Mbytes/s  E0905 11:09:18.791946   586 SocketUtils.cpp:124] non-retryable error encountered during socket io 5 64197 2: Broken pipe [32]
E0905 11:09:18.792007   586 SocketUtils.cpp:124] non-retryable error encountered during socket io 5 0 0: Broken pipe [32]
E0905 11:09:18.792027   586 Sender.cpp:1214] Write error 64197 (262144). fd = 5. port = 22363: Broken pipe [32]
I0905 11:09:18.792060   586 Sender.cpp:722] entered CHECK_FOR_ABORT state 7
I0905 11:09:18.792086   586 Sender.cpp:973] entered PROCESS_ABORT_CMD state 7
W0905 11:09:18.792109   586 Sender.cpp:996] Received abort on 7 remote protocol version 16 remote error code ID_MISMATCH file 100MB-singapore.bin checkpoint 0
W0905 11:09:18.792124   586 WdtBase.cpp:223] Setting the abort code 12
I0905 11:09:18.792139   586 Sender.cpp:1129] Port 22363 done. Transfer status (local) = ABORT, (remote) = ID_MISMATCH. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0595703 (100% overhead). Total bytes = 64258. Wasted bytes due to failure = 64197 (100% overhead). Total throughput = 0 Mbytes/sec
E0905 11:09:18.792309   583 SocketUtils.cpp:124] non-retryable error encountered during socket io 6 61277 2: Broken pipe [32]
E0905 11:09:18.792340   583 Sender.cpp:1230] Transfer aborted during block transfer 22360 100MB-singapore.bin
E0905 11:09:18.792361   583 Sender.cpp:1116] Transfer aborted 22360 ID_MISMATCH
I0905 11:09:18.792377   583 Sender.cpp:1129] Port 22360 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0585938 (100% overhead). Total bytes = 61337. Wasted bytes due to failure = 61277 (100% overhead). Total throughput = 0 Mbytes/sec
E0905 11:09:18.792641   582 SocketUtils.cpp:124] non-retryable error encountered during socket io 4 61280 2: Broken pipe [32]
E0905 11:09:18.792688   582 Sender.cpp:1230] Transfer aborted during block transfer 22359 100MB-singapore.bin
E0905 11:09:18.792701   582 Sender.cpp:1116] Transfer aborted 22359 ID_MISMATCH
I0905 11:09:18.792711   582 Sender.cpp:1129] Port 22359 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0556641 (100% overhead). Total bytes = 61337. Wasted bytes due to failure = 61280 (100% overhead). Total throughput = 0 Mbytes/sec
[                                                 ] 0% 0.0 0.0 Mbytes/s  E0905 11:09:18.810423   581 SocketUtils.cpp:143] transfer aborted during socket io 9 1 2
E0905 11:09:18.810451   581 Sender.cpp:1116] Transfer aborted 22358 ID_MISMATCH
I0905 11:09:18.810461   581 Sender.cpp:1129] Port 22358 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.271484 (100% overhead). Total bytes = 278. Wasted bytes due to failure = 0 (100% overhead). Total throughput = 0 Mbytes/sec
E0905 11:09:18.811182   585 SocketUtils.cpp:143] transfer aborted during socket io 8 42297 2
E0905 11:09:18.811213   585 Sender.cpp:1230] Transfer aborted during block transfer 22362 100MB-singapore.bin
E0905 11:09:18.811236   585 Sender.cpp:1116] Transfer aborted 22362 ID_MISMATCH
I0905 11:09:18.811250   585 Sender.cpp:1129] Port 22362 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0585938 (100% overhead). Total bytes = 42357. Wasted bytes due to failure = 42297 (100% overhead). Total throughput = 0 Mbytes/sec
E0905 11:09:18.814739   580 SocketUtils.cpp:124] non-retryable error encountered during socket io 3 61277 2: Broken pipe [32]
E0905 11:09:18.814767   580 Sender.cpp:1230] Transfer aborted during block transfer 22357 100MB-singapore.bin
E0905 11:09:18.814781   580 Sender.cpp:1116] Transfer aborted 22357 ID_MISMATCH
I0905 11:09:18.814790   580 Sender.cpp:1129] Port 22357 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0585938 (100% overhead). Total bytes = 61337. Wasted bytes due to failure = 61277 (100% overhead). Total throughput = 0 Mbytes/sec
E0905 11:09:18.821446   584 SocketUtils.cpp:143] transfer aborted during socket io 10 42297 2
E0905 11:09:18.821491   584 Sender.cpp:1230] Transfer aborted during block transfer 22361 100MB-singapore.bin
E0905 11:09:18.821512   584 Sender.cpp:1116] Transfer aborted 22361 ID_MISMATCH
I0905 11:09:18.821527   584 Sender.cpp:1129] Port 22361 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0585938 (100% overhead). Total bytes = 42357. Wasted bytes due to failure = 42297 (100% overhead). Total throughput = 0 Mbytes/sec
[                                                 ] 0% 0.0 0.0 Mbytes/s  E0905 11:09:18.935071   579 SocketUtils.cpp:143] transfer aborted during socket io 7 52517 2
E0905 11:09:18.935142   579 Sender.cpp:1230] Transfer aborted during block transfer 22356 100MB-singapore.bin
E0905 11:09:18.935178   579 Sender.cpp:1116] Transfer aborted 22356 ID_MISMATCH
I0905 11:09:18.935196   579 Sender.cpp:1129] Port 22356 done. Transfer status (local) = ABORT, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.0585938 (100% overhead). Total bytes = 52577. Wasted bytes due to failure = 52517 (100% overhead). Total throughput = 0 Mbytes/sec
I0905 11:09:18.935250   579 Sender.cpp:1098] Last thread finished 0.837375
I0905 11:09:18.935696   576 Reporting.cpp:114] Could not send all the bytes 104857600 0
[                                                 ] 0% 0.0 0.0 Mbytes/s  
I0905 11:09:18.935737   576 Sender.cpp:348] Total sender time = 0.83739 seconds (0.000807822 dirTime). Transfer summary : Transfer status (local) = ERROR, (remote) = ID_MISMATCH. Number of blocks transferred = 0. Data Mbytes = 0. Header kBytes = 0.679688 (100% overhead). Total bytes = 385838. Wasted bytes due to failure = 385142 (100% overhead). All files failed.
Total sender throughput = 0 Mbytes/sec (0 Mbytes/sec pure transfer rate)
root@localhost:/relay/dev#

**Comment by nxtreaming** [comment]
I can transfer data after I use -transfer_id to set the transfer id in wdt sender to the value of wdt receiver's transfer_id

Can I avoid specifying the transfer id every time?

Thanks.

**Comment by nxtreaming** [comment]
Closed， ref: https://github.com/facebook/wdt/issues/39

**Comment by fanjiajia** [comment]
有没有方法可以不用每次设置不同的传输id

**Comment by nxtreaming** [comment]
I think you should add a wrapper for wdt.

**Comment by fanjiajia** [comment]
What should I do?Thank you very much

**Comment by nikunjy** [comment]
transfer id is a way to uniquely identify a pair of sender and receiver.
We intentionally generate it if no transfer id is provided 
https://github.com/facebook/wdt/blob/master/Receiver.cpp#L129

Although there is no restriction on you, you could potentially use any transfer id, 
example:   _bin/wdt/wdt -transfer_id=wdt
This will keep the transfer id as you provided.

**Comment by ldemailly** [comment]
the idea here is you start the receiver (tcp
server side) and take the url it produces (which includes the unique transferid, ports, etc)  and pass that to the sender command line

( wdt_e2e_simple_test.sh does that for instance )

**Comment by fanjiajia** [comment]
Every time need to write a different url on the sender command line

**Comment by nikunjy** [comment]
Is there a reason why you do not want to provide with your own transfer id ? 
_bin/wdt/wdt -transfer_id=fanjiajia

If you don't care about identifying each transfer differently then you could potentially provide any non transfer id and keep it the same. If you wanna hack wdt for your own purpose and not force the transfer id, you could change code here https://github.com/facebook/wdt/blob/master/Receiver.cpp#L129

**Comment by fanjiajia** [comment]
I see, thank you .
I have another question.Every time I test "cmake pathtowdtsrcdir -DBUILD_TESTING=on  " when i add the command
"-DBUILD_TESTING=on" the following error will occur.If I skip the command ,it will pass .But it didn't seem to affect the testing of wdt ,i can still in the sender send files.

**Comment by ldemailly** [comment]
it's easiest for you to set transfer_id to wdt or any constant, no need to change the code for that

about the "error" it's missing from your message, can you add it ?

you don't need to build with testing if you just want the "wdt" binary or the .so but I'd like to know if you can't build somehow

**Comment by fanjiajia** [comment]
when i used ./wcp.sh for testing ,Transfer finished, why show transmission speed is "Overall transfer @ 0 Mbytes/sec (20224 ms for 4096 uncompressed)"

**Comment by ldemailly** [comment]
you need a bigger test file - 4k is really not going to matter however you send it

I recommend you use the wdt binary directly unless you have 1 single huge compressible file, which which the wcp wrapper indeed helps but you don't get most of the benefits:

- start your receiver (   wdt --directory /your/destination  -start_port 0 )
- copy the url it outputs (line without the I prefix) e.g
wdt://ldemailly-mbp.local?protocol=15&ports=50123,50124,50125,50126,50127,50128,50129,50130&id=1124845784
- start the sender wdt --directory /your/source --connection_url "theurlfrompreviousstep"

the "" are important so the & don't get interpreted by the shell

obviously you can do all this directly from c++ those example are using the wdt command line

**Comment by fanjiajia** [comment]
when i start the sender 
wdt -directory /usr/local/src -connetcion_url localhost.localdomain?ports=55343,36763,44955,52712,40539,42620,60909,36056&recpv=19&id=431271796   (it provide with the sender)   
it will occur the following:
I0918 15:15:12.260241  7343 wdtCmdLine.cpp:205] Input url: localhost.localdomain?ports=55343,36763,44955,52712,40539,42620,60909,36056
E0918 15:15:12.260288  7343 WdtBase.cpp:53] Url does not specify wdt protocol localhost.localdomain?ports=55343,36763,44955,52712,40539,42620,60909,36056
E0918 15:15:12.260426  7343 WdtBase.cpp:148] Error parsing protocol version 
I0918 15:15:12.260463  7343 Sender.cpp:156] WDT Sender 1.19.1509160 p 19
I0918 15:15:12.260488  7343 DirectorySourceQueue.cpp:125] Root dir now /usr/local/src/WDT/
I0918 15:15:12.260746  7343 WdtBase.cpp:307] Generated a transfer id 1118032236
I0918 15:15:12.260764  7343 WdtBase.cpp:275] using wdt protocol version 19
I0918 15:15:12.260800  7343 wdtCmdLine.cpp:212] Starting sender with details wdt://?ports=&dir=/usr/local/src/WDT/&recpv=19&id=1118032236
I0918 15:15:12.260807  7343 wdtCmdLine.cpp:83] Setting up abort 0 seconds.
I0918 15:15:12.260817  7343 Sender.cpp:376] Client (sending) to , Using ports [ ]
I0918 15:15:12.261312  7343 WdtBase.cpp:295] Throttling not enabled
I0918 15:15:12.262023  7346 Sender.cpp:1333] Progress reporter tracking every 20 ms
I0918 15:15:12.263414  7345 DirectorySourceQueue.cpp:223] Exploring root dir /usr/local/src/WDT/ include_pattern :  exclude_pattern :  prune_dir_pattern : 
I0918 15:15:12.286142  7345 DirectorySourceQueue.cpp:371] Number of files explored: 1718, errors: false

**Comment by ldemailly** [comment]
you forgot the " " around the url

> the "" are important so the & don't get interpreted by the shell

**Comment by fanjiajia** [comment]
I want to konwn ,the difference between the wcp and scp ,in addition to the speed.

**Comment by ldemailly** [comment]
wcp is a shell wrapper script around wdt

you can read it. it's very short : https://github.com/facebook/wdt/blob/master/wcp.sh
