### ISSUE TITLE
Does WDT support streaming mode?

### ISSUE THREAD

**Issue by nxtreaming** [facebook/wdt#86]
Does wdt support to transport (relay) a live streaming content between two hosts?
The content is not a plain whole local file, it is a socket stream.

**Comment by ldemailly** [comment]
WDT has a ByteSource API/Interface but the only implementation today is FileByteSource - so in theory yes, in practice, unless you contribute it, we don't yet have an example of streaming from somewhere else

I do want to add a wdt-wdt proxy at some point too

ps: for quick questions https://gitter.im/facebook/wdt is faster and more interactive, allows for a dialog


does this answer your question ?

Thanks

**Comment by nxtreaming** [comment]
Thanks, I will look at the ByteSource Interface.
