### ISSUE TITLE
Does WDT support to transfer an increasingly directory(example:  there are many files which are generated in time)?

### ISSUE THREAD

**Issue by nxtreaming** [facebook/wdt#99]
We wanna use WDT to transfer increasingly files between two hosts.

**Comment by ldemailly** [comment]
Assuming you mean incrementally, yes if your files are not changing you can use the `- enable_download_resumption` option to send new files

we're also working on something closer to rsync but that's not there yet

https://gitter.im/facebook/wdt is also a good place to ask questions interactively

closing this for now but you can reopen or ask there if you have any followup

thanks!

**Comment by nxtreaming** [comment]
I mean file is generated according to time.
Eg: The folder contains the following files:

file_0001.mp4 , file_0002.mp4, ..., file_n.mp4, file_n+1.mp4....

in other word,  Not all files are available when I start WDT sender. the new files will be generated while WDT sender sends current ( older) files.

**Comment by ldemailly** [comment]
as of right now you would have to restart using download resumption to send subsequent files

but I do want to support a long running mode that keeps sending either by refreshing the directory based on signal or time

or through the -manifest -   which could be coupled to something like fswatch - see issue #6
